### ISSUE TITLE
travis versioning

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/vapour#10]
do min versioning for travis GDAL https://github.com/mpadge/sftest/blob/master/.travis.yml

thanks @mpadge !

**Comment by mpadge** [comment]
You can also do a complie-time version check with`gdalinfo `, and only enable this if supported. I * think* that is robustly OS-independent

**Comment by mdsumner** [comment]
rain day funtimes, see [PROJ](https://github.com/hypertidy/PROJ) for PROJ 4, 5, 6, 7 testing on travis using the system GDAL itself does.

**Comment by mpadge** [comment]
That is awesome!!! Great work!
