### ISSUE TITLE
Install error: object 'f' not found

### ISSUE THREAD

**Issue by jsta** [hypertidy/vapour#15]
I'm having difficulty running `install_github` on master. During compilation I see:

> ...
> ** tests
> ** byte-compile and prepare package for lazy loading
Error in structure(list(source = x, info = raster_info(x)), class = "ssraster") : 
  object 'f' not found
> ...

**Comment by jsta** [comment]
I rolled back to a76ffad9325986e8eac2abf32acc4ca70ce4f3c2 to avoid https://github.com/hypertidy/vapour/blob/master/R/super-simple-raster.R#L22

**Comment by mdsumner** [comment]
Should be fixed now in https://github.com/hypertidy/vapour/commit/208df38f78e575d7bae510c4647e2a8309e51d41

**Comment by mdsumner** [comment]
Pretty sure this is good now, just let me know if you have any problems.
