### ISSUE TITLE
reprex for Windows issue (tried on R 4.0.4 with vapour 0.8.5)

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/vapour#156]
Here's an example, I can run on Windows R 4.0.4 with vapour_0.8.5. If it doesn't work, make a plot of elevation masked to the outline of China in the rnaturalearth::ne_counties polygon within a few seconds, then we might try other tests on what capabilities the install of R has. 

```R

terra_out <- 
  function(x) {
    loadNamespace("terra")
    if (isS4(x) && inherits(x, "SpatRaster")) {
      x <- try(list(extent = c(terra::xmin(x), terra::xmax(x), terra::ymin(x), terra::ymax(x)),
                    dimension = dim(x)[2:1],
                    projection = terra::crs(x), 
                    lonlat = terra::is.lonlat(x), terra = TRUE), silent = TRUE)
      if (inherits(x, "try-error")) stop("cannot use terra grid")
    }
    x  
  }

raster_out <- function(x) {
  loadNamespace("raster")
  if (isS4(x) && inherits(x, "BasicRaster")) {
    ## we have a {raster}
    x <- list(extent = c(x@extent@xmin, x@extent@xmax, x@extent@ymin, x@extent@ymax),
              dimension = c(x@ncols, x@nrows),
              projection = x@crs@projargs, 
              lonlat = raster::couldBeLonLat(x), terra = FALSE)
  }
  x
}
#' Get digital elevation data
#'
#' Read elevation data for any region. 
#' 
#' Currently using GEBCO 2019 as a background, and SRTM 30m resolution for 
#' regions that fit approximately within the size of an SRTM tile (these are 1 degree wide). 
#' 
#' Note that data is streamed into memory, so don't make the dimensions of the 'x' target raster too big. 
#' @param x a terra rast object, any extent any crs and any dims (not too big! - 2000x2000, not 10000x10000)
#' @param ... 
#' @param source a GDAL raster source, to override the inbuild GEBCO + SRTM (in future we might patch in local source)
#' @param threshold a size in degrees above which no SRTM data is queried (about )
#'
#' @return a terra rast object with elevation data
#' @export
#'
#' @examples
#' get_elev(terra::rast())
#' get_elev(raster::raster())
#' 
#' get_elev(raster::raster(raster::extent(80, 120, -60, -40), res = 0.25, crs = "OGC:CRS84"))
#' 
#' get_elev(raster::raster(raster::extent(c(-1, 1, -1, 1) * 25e3), nrows = 1024, ncols = 1024, crs = "+proj=laea +lat_0=44.6371 +lon_0=-63.5923"))
get_elev <- function(x, resample = "bilinear", ..., source = NULL, threshold = 0.5) {
  xraster <- x
  if (inherits(x, "SpatRaster")) {
    x <- terra_out(x)
  } else {
    x <- raster_out(x)
  }
  wh <- c(diff(x$extent[1:2]), diff(x$extent[3:4]))
  no_srtm <- FALSE
  if (x$lonlat) {
    if (max(wh) > threshold) {
      no_srtm <- TRUE
    } 
  } else {
    ## assuming metres ...
    if (max(wh) > (threshold * 111111.12)) {
      no_srtm <- TRUE
    }
  }
  
  if (is.null(source)) {
    rso <- c("/vsicurl/https://public.services.aad.gov.au/datasets/science/GEBCO_2019_GEOTIFF/GEBCO_2019.tif", 
             "/vsicurl/https://opentopography.s3.sdsc.edu/raster/NASADEM/NASADEM_be.vrt")
    if (no_srtm) rso <- rso[1L]
    if (!no_srtm) print("SRTM in use, in addition to GEBCO")
  } else {
    rso <- source
  }
  vals <- vapour::vapour_warp_raster_dbl(rso, extent = x$extent, dimension = x$dimension, projection = x$projection, resample = resample, ...)
  if (x$terra) {
    terra::setValues(xraster, vals)
  } else {
    raster::setValues(xraster, vals)
  }
}



library(terra)

china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
template <- terra::rast(china)

 ## just guessing here, use any template raster ... there are various ways 
##   to define the extent and grain of a region covering China
res(template) <- 0.05 
dem1 <- get_elev(template)
plot(mask(dem1, china))

```

![image](https://user-images.githubusercontent.com/4107631/177001574-9ebfffe1-7978-4ecc-aae0-a7d216baed40.png)

```
vapour::vapour_gdal_version()
[1] "GDAL 3.2.1, released 2020/12/29"
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.5-21

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3        rnaturalearth_0.1.0 magrittr_2.0.3     
 [4] knitr_1.39          units_0.8-0         lattice_0.20-41    
 [7] R6_2.5.1            rlang_1.0.2         fastmap_1.1.0      
[10] highr_0.9           tools_4.0.4         grid_4.0.4         
[13] parallel_4.0.4      xfun_0.30           KernSmooth_2.23-18 
[16] cli_3.2.0           e1071_1.7-9         DBI_1.1.3          
[19] withr_2.5.0         class_7.3-18        htmltools_0.5.2    
[22] yaml_2.3.5          digest_0.6.29       sf_1.0-7           
[25] processx_3.5.3      callr_3.7.0         fs_1.5.2           
[28] ps_1.6.0            codetools_0.2-18    glue_1.6.2         
[31] evaluate_0.15       rmarkdown_2.14      sp_1.4-7           
[34] reprex_2.0.1        proxy_0.4-26        vapour_0.8.5       
[37] compiler_4.0.4      classInt_0.4-3     
```

**Comment by mdsumner** [comment]
@alihassan720 would you mind running this code here? There are two crux likes, inside "system.time()" that I'm interested in how long r says they take to run. 

If they don't run within a minute or two, please just cancel and let me know. The first should run faster for you than for me, but the second will be slower for you. If it's longer than 60s that's too long! I'll need to explore more, thank you. 


```R
##
src1 <- "/vsicurl/https://opentopography.s3.sdsc.edu/raster/COP30/COP30_hh.vrt"

src2 <- "/vsicurl/https://public.services.aad.gov.au/datasets/science/GEBCO_2021_GEOTIFF/GEBCO_2021.tif"

## a local projection about a point
prj <- "+proj=laea +lat_0=29.61 +lon_0=106.4"
ex <- c(-1, 1, -1, 1) * 55000

## attempt 1)
system.time({
  d1 <- vapour::vapour_warp_raster_dbl(src1, extent = ex, projection = prj, dimension = c(512, 512))
})
system.time({
  d2 <- vapour::vapour_warp_raster_dbl(src2, extent = ex, projection = prj, dimension = c(512, 512))
})


## visualize the data
op <- par(mfrow = c(2, 1))
plot(ex[1:2], ex[3:4], asp = 1)
rasterImage(matrix(scales::rescale(d1), 512, byrow = TRUE), ex[1], ex[3], ex[2], ex[4])
plot(ex[1:2], ex[3:4], asp = 1)
rasterImage(matrix(scales::rescale(d2), 512, byrow = TRUE), ex[1], ex[3], ex[2], ex[4])
par(op)
```

![Uploading image.png…]()

**Comment by alihassan720** [comment]
I have tried these codes but for *d1* it gives me an error that is shown below. 
But *d2* is running for the last one hour and still running.
d1 <- vapour::vapour_warp_raster_dbl(src1, extent = ex, projection = prj, dimension = c(512, 512))
})
Error: .onLoad failed in loadNamespace() for 'vapour', details:
  call: register_gdal_cpp()
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'

**Comment by alihassan720** [comment]
> Here's an example, I can run on Windows R 4.0.4 with vapour_0.8.5. If it doesn't work, make a plot of elevation masked to the outline of China in the rnaturalearth::ne_counties polygon within a few seconds, then we might try other tests on what capabilities the install of R has.
> 
> ```r
> terra_out <- 
>   function(x) {
>     loadNamespace("terra")
>     if (isS4(x) && inherits(x, "SpatRaster")) {
>       x <- try(list(extent = c(terra::xmin(x), terra::xmax(x), terra::ymin(x), terra::ymax(x)),
>                     dimension = dim(x)[2:1],
>                     projection = terra::crs(x), 
>                     lonlat = terra::is.lonlat(x), terra = TRUE), silent = TRUE)
>       if (inherits(x, "try-error")) stop("cannot use terra grid")
>     }
>     x  
>   }
> 
> raster_out <- function(x) {
>   loadNamespace("raster")
>   if (isS4(x) && inherits(x, "BasicRaster")) {
>     ## we have a {raster}
>     x <- list(extent = c(x@extent@xmin, x@extent@xmax, x@extent@ymin, x@extent@ymax),
>               dimension = c(x@ncols, x@nrows),
>               projection = x@crs@projargs, 
>               lonlat = raster::couldBeLonLat(x), terra = FALSE)
>   }
>   x
> }
> #' Get digital elevation data
> #'
> #' Read elevation data for any region. 
> #' 
> #' Currently using GEBCO 2019 as a background, and SRTM 30m resolution for 
> #' regions that fit approximately within the size of an SRTM tile (these are 1 degree wide). 
> #' 
> #' Note that data is streamed into memory, so don't make the dimensions of the 'x' target raster too big. 
> #' @param x a terra rast object, any extent any crs and any dims (not too big! - 2000x2000, not 10000x10000)
> #' @param ... 
> #' @param source a GDAL raster source, to override the inbuild GEBCO + SRTM (in future we might patch in local source)
> #' @param threshold a size in degrees above which no SRTM data is queried (about )
> #'
> #' @return a terra rast object with elevation data
> #' @export
> #'
> #' @examples
> #' get_elev(terra::rast())
> #' get_elev(raster::raster())
> #' 
> #' get_elev(raster::raster(raster::extent(80, 120, -60, -40), res = 0.25, crs = "OGC:CRS84"))
> #' 
> #' get_elev(raster::raster(raster::extent(c(-1, 1, -1, 1) * 25e3), nrows = 1024, ncols = 1024, crs = "+proj=laea +lat_0=44.6371 +lon_0=-63.5923"))
> get_elev <- function(x, resample = "bilinear", ..., source = NULL, threshold = 0.5) {
>   xraster <- x
>   if (inherits(x, "SpatRaster")) {
>     x <- terra_out(x)
>   } else {
>     x <- raster_out(x)
>   }
>   wh <- c(diff(x$extent[1:2]), diff(x$extent[3:4]))
>   no_srtm <- FALSE
>   if (x$lonlat) {
>     if (max(wh) > threshold) {
>       no_srtm <- TRUE
>     } 
>   } else {
>     ## assuming metres ...
>     if (max(wh) > (threshold * 111111.12)) {
>       no_srtm <- TRUE
>     }
>   }
>   
>   if (is.null(source)) {
>     rso <- c("/vsicurl/https://public.services.aad.gov.au/datasets/science/GEBCO_2019_GEOTIFF/GEBCO_2019.tif", 
>              "/vsicurl/https://opentopography.s3.sdsc.edu/raster/NASADEM/NASADEM_be.vrt")
>     if (no_srtm) rso <- rso[1L]
>     if (!no_srtm) print("SRTM in use, in addition to GEBCO")
>   } else {
>     rso <- source
>   }
>   vals <- vapour::vapour_warp_raster_dbl(rso, extent = x$extent, dimension = x$dimension, projection = x$projection, resample = resample, ...)
>   if (x$terra) {
>     terra::setValues(xraster, vals)
>   } else {
>     raster::setValues(xraster, vals)
>   }
> }
> 
> 
> 
> library(terra)
> 
> china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
> template <- terra::rast(china)
> 
>  ## just guessing here, use any template raster ... there are various ways 
> ##   to define the extent and grain of a region covering China
> res(template) <- 0.05 
> dem1 <- get_elev(template)
> plot(mask(dem1, china))
> ```
> 
> ![image](https://user-images.githubusercontent.com/4107631/177001574-9ebfffe1-7978-4ecc-aae0-a7d216baed40.png)
> 
> ```
> vapour::vapour_gdal_version()
> [1] "GDAL 3.2.1, released 2020/12/29"
> > sessionInfo()
> R version 4.0.4 (2021-02-15)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19044)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
> [3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
> [5] LC_TIME=English_Australia.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] terra_1.5-21
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.8.3        rnaturalearth_0.1.0 magrittr_2.0.3     
>  [4] knitr_1.39          units_0.8-0         lattice_0.20-41    
>  [7] R6_2.5.1            rlang_1.0.2         fastmap_1.1.0      
> [10] highr_0.9           tools_4.0.4         grid_4.0.4         
> [13] parallel_4.0.4      xfun_0.30           KernSmooth_2.23-18 
> [16] cli_3.2.0           e1071_1.7-9         DBI_1.1.3          
> [19] withr_2.5.0         class_7.3-18        htmltools_0.5.2    
> [22] yaml_2.3.5          digest_0.6.29       sf_1.0-7           
> [25] processx_3.5.3      callr_3.7.0         fs_1.5.2           
> [28] ps_1.6.0            codetools_0.2-18    glue_1.6.2         
> [31] evaluate_0.15       rmarkdown_2.14      sp_1.4-7           
> [34] reprex_2.0.1        proxy_0.4-26        vapour_0.8.5       
> [37] compiler_4.0.4      classInt_0.4-3     
> ```
I have get the elevation data by this codes but I need (SRTM 1 Arc-Second Global) for China. Let me know how i can get this.
library(raster)
china = getData("alt", country = "China", mask= T)
plot(china)

**Comment by mdsumner** [comment]
> I have tried these codes but for _d1_ it gives me an error that is shown below. But _d2_ is running for the last one hour and still running. d1 <- vapour::vapour_warp_raster_dbl(src1, extent = ex, projection = prj, dimension = c(512, 512)) }) Error: .onLoad failed in loadNamespace() for 'vapour', details: call: register_gdal_cpp() error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'

this is a broken R installation, you'll need to update packages and make sure `library(Rcpp)` and `library(vapour)` at least work.  I'm assuming you can run the code I'm just interested in how long it takes

**Comment by alihassan720** [comment]
Yes, it's working now, please let me know how I can get to China

**Comment by mdsumner** [comment]
excellent, thank you that's good to know. 


For that you can do 

```R
src <- "/vsicurl/https://opentopography.s3.sdsc.edu/raster/COP30/COP30_hh.vrt"
library(terra)
china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
template <- terra::rast(china)

## ~450m
res(template) <- (15/60/60) 

srtm <- get_elev(template, source = src)

```

I've used a different opentopography source, the COP30 - I'm still learning about these myself. 

note that object will be about 1Gb, so it starts to get to a point where you don't want to pull it into memory, and you're getting out of bounds of what the vapour stuff is for. 



In theory terra alone would work like this, and you could pass it out to file (but I'm not sure how long this takes)

```R
library(terra)
src <- "/vsicurl/https://opentopography.s3.sdsc.edu/raster/COP30/COP30_hh.vrt"
china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
template <- terra::rast(china)

res(template) <- (15/60/60) 
srtm2 <- project(rast(src), template, filename = "myfile.tif")

```

**Comment by alihassan720** [comment]
> excellent, thank you that's good to know.
> 
> For that you can do
> 
> ```r
> src <- "/vsicurl/https://opentopography.s3.sdsc.edu/raster/COP30/COP30_hh.vrt"
> library(terra)
> china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
> template <- terra::rast(china)
> 
> ## ~450m
> res(template) <- (15/60/60) 
> 
> srtm <- get_elev(template, source = src)
> ```
> 
> I've used a different opentopography source, the COP30 - I'm still learning about these myself.
> 
> note that object will be about 1Gb, so it starts to get to a point where you don't want to pull it into memory, and you're getting out of bounds of what the vapour stuff is for.
> 
> In theory terra alone would work like this, and you could pass it out to file (but I'm not sure how long this takes)
> 
> EDIT: actually, I wouldn't try this it takes forever - I can't see how to make terra pick the right zoom level (which is what my vapour code does automatically).
> 
> ```r
> #library(terra)
> #src <- "/vsicurl/https://opentopography.s3.sdsc.edu/raster/COP30/COP30_hh.vrt"
> #china <- vect(rnaturalearth::ne_countries(country = "China", returnclass = "sf"))
> #template <- terra::rast(china)
> 
> #res(template) <- (15/60/60) 
> #srtm2 <- project(rast(src), template, filename = "myfile.tif")
> ```

Sorry, I think that both codes are not working, After passing four days on the supercomputer it's still running.

**Comment by mdsumner** [comment]
I can't add anything to this, please think about what you can do to test smaller parts of the process and provide useful feedback.

There is a list of .tif files in that vrt url  Perhaps try a few ops with one.
