### ISSUE TITLE
Error when first source has fewer bands than later ones.

### ISSUE THREAD

**Issue by h-a-graham** [hypertidy/vapour#169]
Hey @mdsumner - hope you're good?

Came across this interesting error - see this reprex: 

``` r
library(terra)
#> terra 1.6.14
library(vapour)

f <- system.file("ex/elev.tif", package="terra") 
r.terra <- terra::rast(f)

# create src with 2 bands
r.terra2 <- c(r.terra, sqrt(r.terra))|>
  writeRaster(tempfile(fileext = ".tif"))|>
  sources()
#create src with 3 bands
r.terra3 <- c(r.terra, sqrt(r.terra), sqrt(r.terra)*10)|>
  writeRaster(tempfile(fileext = ".tif"))|>
  sources()

# vector of sources
srcs1 <- c( r.terra3, r.terra2)
srcs2 <- c( r.terra2, r.terra3)
#get original info for this example
info <- vapour::vapour_raster_info(f)

vap_func <- function(src){
  vapour::vapour_warp_raster(src, 
                             bands=1:2,
                             extent=info$extent,
                             dimension = info$dimension,
                             projection = info$projection)
}

# this works as expected...
x <- vap_func(srcs1)

# this fails where the source with fewer bands comes first in the src list.
y <- vap_func(srcs2)
#> Warning: Destination dataset has 2 bands, but at least 3 are needed (GDAL error
#> 1)
#> Error in warp_in_memory_gdal_cpp(x, source_WKT = source_projection, target_WKT = projection, : something went wrong!
```

<sup>Created on 2022-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So, I'm curious to know your thoughts here - is this the intended behaviour? Obviously, the ordering of the sources really matters so it may be the case here that I want to have the raster with 2 bands first. I see this is a GDAL error rather than vapour (as it also throws the same error when using straight gdal or sf). 

My guess is that the output source template is derived from the first source, right? But this seems a little odd - I mean, shouldn't it fail in both cases if we just shouldn't use the warper for sources with a different number of bands? 

So I guess, from my perspective, I can catch this error and add NA bands for rasters with fewer bands than the max in the source list. This is however, a bit hacky. Maybe warping sources with different numbers of bands should cause an error regardless of the order? 

Cheers and thanks again for this awesome package!

**Comment by mdsumner** [comment]
hey thanks for the example, I kind of worried about this case and decided it could be worked around by looping over bands at worst- I'm not sure  how to fix but I will have a look. Thanks for letting me know, atm I can't see how to fix it but longer term I'll figure it out. 

you can 'vapour_vrt(src, bands = )' if that helps to pick out bands at a time (you'll get NA if any band choice is not in a source so need to remove those)

**Comment by h-a-graham** [comment]
Great - thanks for the reply, mate. That makes sense and will be a good work around. Definitely not a priority for my stuff right now but I know how much you love these edge cases!
Cheers!

**Comment by mdsumner** [comment]
actually, gdalwarp does the same thing - with srcs2 order you get 2 bands, with srcs1 order you get 3: 

```R
system(sprintf("gdalwarp %s %s out2.vrt", srcs2[1], srcs2[2]))
system(sprintf("gdalwarp %s %s out3.vrt", srcs1[1], srcs1[2])

vapour_raster_Info("out2.vrt")$bands
[1] 2
vapour_raster_Info("out3.vrt")$bands
[1] 3
```


So, I'm not sure how this could be changed in vapour, and maybe it should not. 👍

**Comment by h-a-graham** [comment]
Ah so this is super interesting - so if you write to a tif file rather than a vrt it will still throw an error. 

```
 system(sprintf("gdalwarp %s %s out2.tif", srcs2[1], srcs2[2]))

Creating output file that is 95P x 90L.
Processing /tmp/RtmpktuyVb/file442225893c7.tif [1/2] : 0Using internal nodata values (e.g. nan) for image /tmp/RtmpktuyVb/file442225893c7.tif.
Copying nodata values from source /tmp/RtmpktuyVb/file442225893c7.tif to destination out2.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
Processing /tmp/RtmpktuyVb/file4422782a351b.tif [2/2] : 

0ERROR 1: Destination dataset has 2 bands, but at least 3 are needed
```
Right, okay -  in that case, I might be tempted to force the user to sort out band numbering before warping or at least warn on it...  
Can you think of a good reason why you would want to use multiple sources with a differing number of bands?

**Comment by mdsumner** [comment]
Not really... maybe it's just a way of allowing any old inputs but templating on the first.

It still confuses me a bit, I might ask on the mailing list ay some point 👌

**Comment by mdsumner** [comment]
there might be more to it, but arguably you might expect to template on the input with the most bands, but also should you find the best common band data type etc etc

**Comment by mdsumner** [comment]
confusing! lots of options to keep in head to think aboutvit 😃

**Comment by mdsumner** [comment]
if you have more on this please feel free to reopen

**Comment by mdsumner** [comment]
this might be relevant going forward https://github.com/OSGeo/gdal/pull/6985
