### ISSUE TITLE
Issue with cross compiling

### ISSUE THREAD

**Issue by jeroen** [hypertidy/vapour#223]
There is currently no arm64 macos binary on r-universe because the cross compiling fails: https://github.com/r-universe/hypertidy/actions/runs/7477318066/job/20349896987

The same fix in sf: https://github.com/r-spatial/sf/pull/2269/files

Basically when cross compiling, the configure script can build but not execute test programs.

**Comment by mdsumner** [comment]
thanks! seems to be working now

**Comment by jeroen** [comment]
Awesome thanks!
