### ISSUE TITLE
ExecuteSQL SpatialFilter

### ISSUE THREAD

**Issue by jsta** [hypertidy/vapour#34]
I see that `vapour` currently passes `NULL` to the SpatialFilter argument of the [ExecuteSQL](https://www.gdal.org/ogr_sql.html#ogr_sql_exec_sql) function:

https://github.com/hypertidy/vapour/blob/465b2a6b5748ea4e62ab020aad0a52e3db334c28/src/vapour.cpp#L309

I realize this may be a big ask, but how difficult would it be to enable passing a bounding box instead?

**Comment by mdsumner** [comment]
Good question! I'm happy to try to find out, probably @mpadge will know more easily than I?  I'm interested to find ou about these other extended options too, just hadn't gotten to it - any exploration welcome :)

**Comment by jsta** [comment]
This is the equivalent `gdalUtils` command:

```
tfile <- tempfile(ext = "gpkg")
ogr2ogr(gdb_path, tfile, layer = "some_layer", spat = st_bbox(some_sf), f = "GPKG")
```

**Comment by mpadge** [comment]
Yeah that's really easy to implement. I'll give it a go next week.

**Comment by mdsumner** [comment]
Given 'vapour_read_extrnt', is this really needed? I'm not saying we shouldn't expose more GDAL (we should!). But with the extents (bboxes) I think this is simple in R only.

**Comment by mpadge** [comment]
Sorry for dropping this one, but yeah, agreed @mdsumner that it's likely easier in R. Moreover, remember I did a timing comparison somewhere using the SQL filters in GDAL, and it was actually slower than post-filtering with `sf`? [... more organised me inserts relevant link here ...]

**Comment by mdsumner** [comment]
I will probably do it, just so we can!

It's been discussed over at sf, and it inspired me to build on Barry's PR for ExecuteSQL and do the DBI thing: 

https://github.com/mdsumner/RGDALDB

(Not the first time I tried to do exactly that ... but this time I really got somewhere).

**Comment by jsta** [comment]
I'm having trouble telling if this functionality has been implemented yet here or in a different package. Should I look for it in `RGDALDB`?

**Comment by mdsumner** [comment]
Er, no - it's here but only in C++: 

https://github.com/hypertidy/vapour/blob/master/src/vapour.cpp#L251

ex is a numeric vector xmin, xmax, ymin, ymax,

I can't expose this to R right now, only because it's late at night and I won't be able to check it carefully - I just haven't gotten back to this.

**Comment by mdsumner** [comment]
I did it, let me know

``` r
file <- "list_locality_postcode_meander_valley.tab"
mvfile <- system.file(file.path("extdata/tab", file), package="vapour")

## doesn't need names, they aren't used
## order is assumed
e <- c(xmin = 469750, xmax = 500840, 
       ymin = 5381892, ymax = 5393322)

library(vapour)
## no change
length(vapour_read_geometry(mvfile, extent = e))
#> [1] 58

## needs sql to be run as well
g <- vapour_read_geometry(mvfile, extent = e, sql = "SELECT * FROM list_locality_postcode_meander_valley")
length(g)  ## 9, they intersect the bounding box / extent
#> [1] 9


## compare with sf plot
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.3.2, PROJ 4.9.3
x <- sf::read_sf(mvfile)
plot(x[1], reset = F)
plot(sf::st_cast(sf::st_as_sfc(g)), add = TRUE, lwd =5)
rect(e[1], e[3], e[2], e[4])
```

![](https://i.imgur.com/uXSGBTb.png)

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
didn't mean to close it ...

**Comment by mdsumner** [comment]
Yes, for sure - I should have done it at the time

**Comment by mdsumner** [comment]
All done now.  Upcoming NEWS item: 

```
Vector read functions gain new `extent` argument to apply a spatial filter in conjunction with 
 the `sql` argument, per discussion #34. The extent can be of type sp, sf, raster, or generic 
 vector `c(xmin, xmax, ymin, ymax)`.  The extent is ignored if the `sql` argument is not specified, 
 with a warning.  Applies to `vapour_geom_summary`,  `vapour_read_attributes`, `vapour_read_extent`, 
 `vapour_read_geometry`, `vapour_read_geometry_text`, and `vapour_read_names`. 
```


Please check, but create new issues for specific problems.
