### ISSUE TITLE
hellish bug

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/vapour#7]
The read_geometry_text examples include a direct path to inst/filename.something, and I think this causes a total lock up in RStudio - I've had to soft reboot each time with check, and just running examples. 

Don't do that in examples ...

**Comment by mpadge** [comment]
Yeah, do that, but don't allow exported fns to directly call `Rcpp` fns. Just provide simple `R` wrappers in all cases and check for file existence and appropriate type before calling `Rcpp`.

**Comment by mdsumner** [comment]
I can't reproduce this problem now so I may have been mistaken about what it was.  An empty string, non-existent file, weird local file in check, these all fail gracefully at the GDAL level. It needs to be arbitrary because it might be a driver-specific string i.e. 'ODBC:dsn,table,etc' or a URL. 

I'll reconsider the export to .R process generally, thanks!
