### ISSUE TITLE
Supressing "manually finding feature count" message

### ISSUE THREAD

**Issue by jsta** [hypertidy/vapour#73]
[This line](https://github.com/hypertidy/vapour/blob/f1e28db9eb4160db03b2a7f4ccdf28e62ae20198/src/vapour.cpp#L304) uses the `Rprintf` function to print the message "manually finding feature count" to the console. 

I would like to suppress this message as it throws off progress bar printing in my code. However, it seems like there is no good way to suppress it. The `capture.output` solution offered [here](https://stackoverflow.com/q/28327013/3362993) doesn't do it because the `sf` structure of the returned object is not preserved. It looks like all the `Rcpp` docs recommend `Rprintf` but is there a way to turn off this message?

**Comment by mdsumner** [comment]
I don't think so, now I think I would just remove it - it's required fairly often (to find the count manually) and the message is not actually helpful
